name: thaichana_helper
description: Thai chana helper application.

publish_to: 'none' 

version: 1.0.10+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

  permission_handler: '^3.0.0'
  flutter_qr_reader: ^1.0.3
  webview_flutter: ^0.3.22
  shared_preferences: ^0.5.7+3
  # share: ^0.5.3
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "สแกนไทยชนะ"
  ios: true
  image_path: "assets/icon/icon.png"
  
flutter:
  assets:
    - assets/icon/icon.png

  uses-material-design: true
